# Generated by Django 6.0.5 on 2026-05-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBDApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectiondetail',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='sectiondetail',
            name='button_text',
        ),
        migrations.AddField(
            model_name='sectiondetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='section/'),
        ),
    ]
