# Generated by Django 6.0.5 on 2026-05-22 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBDApp', '0002_remove_sectiondetail_button_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeOfferCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='we_offer_category/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeOfferDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='we_offer/')),
                ('points', models.TextField(blank=True, null=True)),
                ('assurance', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='we_offers', to='PBDApp.weoffercategory')),
            ],
        ),
        migrations.DeleteModel(
            name='WeOffer',
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('commitment', 'Commitment'), ('goal', 'Goal'), ('prime-services', 'Prime Services'), ('about-us', 'About Us'), ('journey', 'Journey'), ('growth-section', 'Growth Section'), ('highlights', 'Highlights')], max_length=50),
        ),
    ]
