# Generated by Django 6.0.5 on 2026-05-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBDApp', '0003_weoffercategory_weofferdetail_delete_weoffer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='our_visibility/')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
