# Generated by Django 6.0.5 on 2026-05-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBDApp', '0004_ourvisibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weofferdetail',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
