# Generated by Django 6.0.5 on 2026-05-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PBDApp', '0005_alter_weofferdetail_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weofferdetail',
            name='heading',
        ),
    ]
