# Generated by Django 6.0.5 on 2026-05-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PBDApp', '0006_remove_weofferdetail_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedproject',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='completedproject',
            name='title',
        ),
    ]
