# Generated by Django 6.0.5 on 2026-05-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBDApp', '0008_upcomingprojects_upcomingprojectoverview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('home', 'Home'), ('journey', 'Journey'), ('offer', 'Offer'), ('projects', 'Projects'), ('upcoming', 'Upcoming'), ('services', 'Services')], max_length=50)),
                ('image', models.ImageField(upload_to='banner_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
