# Generated by Django 6.0.5 on 2026-05-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBDApp', '0009_bannerimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='herovideo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
